/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './google-chart.component';
import * as import2 from '../google-charts-loader.service';
const styles_GoogleChartComponent:any[] = ([] as any[]);
export const RenderType_GoogleChartComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_GoogleChartComponent,
  data: {}
}
);
export function View_GoogleChartComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(2,[(l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)))],(null as any),(null as any));
}
function View_GoogleChartComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'google-chart',([] as any[]),(null as any),(null as any),(null as any),View_GoogleChartComponent_0,RenderType_GoogleChartComponent)),
    import0.ɵdid(573440,(null as any),0,import1.GoogleChartComponent,[
      import0.ElementRef,
      import2.GoogleChartsLoaderService
    ]
    ,(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const GoogleChartComponentNgFactory:import0.ComponentFactory<import1.GoogleChartComponent> = import0.ɵccf('google-chart',import1.GoogleChartComponent,View_GoogleChartComponent_Host_0,{data: 'data'},{
  chartReady: 'chartReady',
  chartError: 'chartError',
  chartSelect: 'chartSelect',
  mouseOver: 'mouseOver'
}
,([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JsYWtlcC9Qcm9qZWN0cy9uZzItZ29vZ2xlLWNoYXJ0cy9zcmMvZ29vZ2xlLWNoYXJ0L2dvb2dsZS1jaGFydC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYmxha2VwL1Byb2plY3RzL25nMi1nb29nbGUtY2hhcnRzL3NyYy9nb29nbGUtY2hhcnQvZ29vZ2xlLWNoYXJ0LmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2JsYWtlcC9Qcm9qZWN0cy9uZzItZ29vZ2xlLWNoYXJ0cy9zcmMvZ29vZ2xlLWNoYXJ0L2dvb2dsZS1jaGFydC5jb21wb25lbnQudHMuR29vZ2xlQ2hhcnRDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2JsYWtlcC9Qcm9qZWN0cy9uZzItZ29vZ2xlLWNoYXJ0cy9zcmMvZ29vZ2xlLWNoYXJ0L2dvb2dsZS1jaGFydC5jb21wb25lbnQudHMuR29vZ2xlQ2hhcnRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2PjwvZGl2PiIsIjxnb29nbGUtY2hhcnQ+PC9nb29nbGUtY2hhcnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkNBQTs7OztJQ0FBO2dCQUFBOzs7SUFBQTtLQUFBOzs7Ozs7Ozs7OyJ9
