/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './google-chart.component';
import * as import2 from '../google-charts-loader.service';
const styles_GoogleChartComponent:any[] = ([] as any[]);
export const RenderType_GoogleChartComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_GoogleChartComponent,
  data: {}
}
);
export function View_GoogleChartComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(2,[(l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)))],(null as any),(null as any));
}
function View_GoogleChartComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'google-chart',([] as any[]),(null as any),(null as any),(null as any),View_GoogleChartComponent_0,RenderType_GoogleChartComponent)),
    import0.ɵdid(286720,(null as any),0,import1.GoogleChartComponent,[
      import0.ElementRef,
      import2.GoogleChartsLoaderService
    ]
    ,(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const GoogleChartComponentNgFactory:import0.ComponentFactory<import1.GoogleChartComponent> = import0.ɵccf('google-chart',import1.GoogleChartComponent,View_GoogleChartComponent_Host_0,{data: 'data'},{
  chartReady: 'chartReady',
  chartError: 'chartError',
  chartSelect: 'chartSelect',
  mouseOver: 'mouseOver'
}
,([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Jid29yazMvbmcyLWdvb2dsZS1jaGFydHMvc3JjL2dvb2dsZS1jaGFydC9nb29nbGUtY2hhcnQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2Jid29yazMvbmcyLWdvb2dsZS1jaGFydHMvc3JjL2dvb2dsZS1jaGFydC9nb29nbGUtY2hhcnQuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYmJ3b3JrMy9uZzItZ29vZ2xlLWNoYXJ0cy9zcmMvZ29vZ2xlLWNoYXJ0L2dvb2dsZS1jaGFydC5jb21wb25lbnQudHMuR29vZ2xlQ2hhcnRDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2Jid29yazMvbmcyLWdvb2dsZS1jaGFydHMvc3JjL2dvb2dsZS1jaGFydC9nb29nbGUtY2hhcnQuY29tcG9uZW50LnRzLkdvb2dsZUNoYXJ0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdj48L2Rpdj4iLCI8Z29vZ2xlLWNoYXJ0PjwvZ29vZ2xlLWNoYXJ0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7eUJDQUE7Ozs7SUNBQTtnQkFBQTs7O0lBQUE7S0FBQTs7Ozs7Ozs7OzsifQ==
