/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './google-charts.module';
import * as import2 from './google-charts-loader.service';
class Ng2GoogleChartsModuleInjector extends import0.ɵNgModuleInjector<import1.Ng2GoogleChartsModule> {
  _Ng2GoogleChartsModule_0:import1.Ng2GoogleChartsModule;
  __GoogleChartsLoaderService_1:import2.GoogleChartsLoaderService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _GoogleChartsLoaderService_1():import2.GoogleChartsLoaderService {
    if ((this.__GoogleChartsLoaderService_1 == null)) { (this.__GoogleChartsLoaderService_1 = new import2.GoogleChartsLoaderService()); }
    return this.__GoogleChartsLoaderService_1;
  }
  createInternal():import1.Ng2GoogleChartsModule {
    this._Ng2GoogleChartsModule_0 = new import1.Ng2GoogleChartsModule();
    return this._Ng2GoogleChartsModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Ng2GoogleChartsModule)) { return this._Ng2GoogleChartsModule_0; }
    if ((token === import2.GoogleChartsLoaderService)) { return this._GoogleChartsLoaderService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2GoogleChartsModuleNgFactory:import0.NgModuleFactory<import1.Ng2GoogleChartsModule> = new import0.NgModuleFactory<any>(Ng2GoogleChartsModuleInjector,import1.Ng2GoogleChartsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JsYWtlcC9Qcm9qZWN0cy9uZzItZ29vZ2xlLWNoYXJ0cy9zcmMvZ29vZ2xlLWNoYXJ0cy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYmxha2VwL1Byb2plY3RzL25nMi1nb29nbGUtY2hhcnRzL3NyYy9nb29nbGUtY2hhcnRzLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
